import React from 'react';

/* eslint-disable linebreak-style */
/* eslint-disable no-unused-vars */
var data = [
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 277,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 278,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 279,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 280,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 281,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 282,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 283,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 284,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 285,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 286,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 287,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 288,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 289,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 290,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 291,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 292,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 293,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 294,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 295,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 296,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 297,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 298,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 299,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 300,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 301,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 302,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 303,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 304,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 305,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 306,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 307,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 308,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 309,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 310,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 311,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 312,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 313,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 314,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 315,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 316,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_F',
		pk: 317,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.337594085092824,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 318,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 319,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.849732204797104,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 320,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 321,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 322,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 323,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 324,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 325,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 326,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 327,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 328,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 329,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 330,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 331,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.772230799214098,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 332,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 333,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 334,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 335,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 336,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 337,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 338,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 339,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 340,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 341,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 342,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 343,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.775367001152526,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 344,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 345,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 346,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 347,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 348,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 349,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 350,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 351,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 352,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_F',
		pk: 353,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.36931206040883,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 354,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 355,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.818640737972964,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 356,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 357,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 358,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 359,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 360,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 361,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 362,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 363,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 364,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_F',
		pk: 365,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.438528863651555,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 366,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.83743366324162,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 367,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.804179360082036,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 368,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 369,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 370,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 371,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 372,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 373,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 374,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 375,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 376,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_F',
		pk: 377,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.419310945569002,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 378,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.818101578189128,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 379,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 380,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 381,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 382,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 383,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 384,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 385,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 386,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 387,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 388,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 389,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 390,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 391,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 392,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 393,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 394,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 395,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 396,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 397,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 398,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 399,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 400,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 401,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 402,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 403,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.794563570820255,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 404,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 405,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 406,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 407,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 408,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 10,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 409,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 410,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 411,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 412,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 413,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 414,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 415,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.82645598315557,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 416,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 417,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 418,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 419,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 420,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 11,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 421,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 422,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 423,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 424,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 425,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 426,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 427,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 428,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 429,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 430,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 431,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 432,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 12,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 433,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 434,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 435,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 436,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 437,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 438,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 439,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 440,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 441,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 442,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 443,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 444,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 13,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 445,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 446,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 447,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 448,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 449,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 450,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 451,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.781689278812769,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 452,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 453,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 454,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 455,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 456,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 14,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 457,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 458,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 459,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 460,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 461,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 462,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 463,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.836185114339706,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 464,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 465,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 466,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 467,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 468,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 15,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 469,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 470,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 471,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 472,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_F',
		pk: 473,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.3259384112421,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 474,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 475,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.960300370984762,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 476,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 477,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 478,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 479,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 480,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 16,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 481,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 482,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 483,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 484,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 485,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 486,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 487,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 488,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 489,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 490,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 491,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 492,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 17,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 493,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 494,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 495,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 496,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 497,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 498,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 499,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 500,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 501,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 502,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 503,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 504,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 18,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 505,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 506,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 507,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 508,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 509,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 510,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_D',
		pk: 511,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.849500388722633,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 512,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 513,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 514,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 515,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 516,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 19,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 517,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 518,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 519,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 520,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 521,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 522,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 523,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.843392311760575,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 524,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 525,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 526,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 527,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 528,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 20,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 529,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 530,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 531,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 532,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 533,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 534,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 535,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 536,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 537,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 538,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 539,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 540,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 21,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 541,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 542,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 543,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 544,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 545,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 546,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 547,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 548,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 549,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 550,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 551,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 552,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 22,
		reference_video_name: 'Caterpillar.webm',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1133,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.989975986038669,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1134,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.949713293637589,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1135,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.880555207209889,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1136,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1137,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1138,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1139,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1140,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1141,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1142,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1143,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1144,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 0,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1145,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.915652832078377,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1146,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.942029450332287,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1147,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.947885582510221,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1148,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.838157139670697,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1149,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1150,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1151,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1152,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1153,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1154,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1155,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1156,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 1,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1157,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.898793429431536,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1158,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.943162050107487,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1159,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.949496487113218,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1160,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.955083237658606,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1161,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1162,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1163,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1164,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1165,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.857767514142171,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1166,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1167,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1168,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 2,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1169,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1170,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1171,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1172,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_C',
		pk: 1173,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.730336075146811,
	},
	{
		match_level: 'MatchLevel.LEVEL_C',
		pk: 1174,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.65549916589203,
	},
	{
		match_level: 'MatchLevel.LEVEL_C',
		pk: 1175,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.69908829802247,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1176,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1177,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1178,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1179,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1180,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 3,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1181,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1182,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1183,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1184,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_C',
		pk: 1185,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.750232155901222,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1186,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.979153138187427,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1187,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1188,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1189,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1190,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1191,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1192,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 4,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1193,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1194,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1195,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1196,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1197,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1198,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1199,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.918866943213968,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1200,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1201,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1202,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1203,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1204,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 5,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1205,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1206,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1207,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1208,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.928755441588135,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1209,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1210,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1211,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1212,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.958369073892166,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1213,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.98226532589913,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1214,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.946369575414109,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1215,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.846264418282017,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1216,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 6,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.822569043090264,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1217,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1218,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1219,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1220,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1221,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1222,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1223,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1224,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.869320019052733,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1225,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.975750492885074,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1226,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.980859734154198,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1227,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.845532972469214,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1228,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 7,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.853872862613548,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1229,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1230,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1231,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1232,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1233,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1234,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1235,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1236,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.85180034238199,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1237,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.853437667943306,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1238,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.868726268757354,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1239,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.978894524092945,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1240,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 8,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.926708471114625,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1241,
		query_segment_id: 0,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1242,
		query_segment_id: 1,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1243,
		query_segment_id: 2,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1244,
		query_segment_id: 3,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1245,
		query_segment_id: 4,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1246,
		query_segment_id: 5,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1247,
		query_segment_id: 6,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_G',
		pk: 1248,
		query_segment_id: 7,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.0,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1249,
		query_segment_id: 8,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.844048758839381,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1250,
		query_segment_id: 9,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.854249722145415,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1251,
		query_segment_id: 10,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.906770132997493,
	},
	{
		match_level: 'MatchLevel.LEVEL_A',
		pk: 1252,
		query_segment_id: 11,
		query_video_name: 'Megamind.avi',
		reference_segment_id: 9,
		reference_video_name: 'Megamind_bugy.avi',
		similarity_score: 0.978644352870349,
	},
];

class Visualization extends React.Component {
	componentDidMount() {
		const canvas = this.refs.canvas;
		const c = canvas.getContext('2d');
		/* eslint-disable no-undef */
		/* eslint-disable prefer-destructuring */
		//Hämtar unika videonamn som finns i listan.
		// function UniqueVideoNames() {
		// 	const query_video_names = data.map(o => o.query_video_name); //Alla query videonamn
		// 	const reference_video_names = data.map(o => o.reference_video_name); //Alla reference videonamn
		// 	const allNames = [...query_video_names, ...reference_video_names]; //Alla!
		// 	const allUniqueNames = [...new Set(allNames)]; //Unika videonman

		// 	return allUniqueNames;
		// }

		//Räknar ut en videos längd och retunerar dess maxvärde.
		function videoLength(videoName) {
			const queryName = data.filter(obj => obj.query_video_name === videoName); //Hämtar alla objekt för videonamn som passar
			const referenceName = data.filter(obj => obj.reference_video_name === videoName); //Hämtar alla objekt för videonamn som passar
			const query_segment_ids = queryName.map(o => o.query_segment_id); //Alla query Ids om det finns.
			const max_query_segment_id = [...new Set(query_segment_ids)].length; //Längd av query video, 0 om det inte är en queryvideo.
			const reference_segment_ids = referenceName.map(o => o.reference_segment_id); //Alla reference Ids om det finns.
			const max_reference_segment_id = [...new Set(reference_segment_ids)].length; // Längd av reference video, 0 om det inte är en referencevideo.

			return Math.max(max_query_segment_id, max_reference_segment_id); //Retunerar längden av den video som innehåller något.
		}

		//Klass för att rendera rektanglar för videosegment.
		class Rectangle {
			constructor(x, y, w, h) {
				this.x = x;
				this.y = y;
				this.w = w;
				this.h = h;

				this.isHovered = false;
				this.path = new Path2D();
				this.path.rect(x, y, w, h);
				this.lines = [];
			}

			addLines(line) {
				this.lines.push(line);
			}

			setIsHovered(ToF) {
				this.isHovered = ToF;
				this.lines.forEach(l => {
					if (!l.recIsActive) {
						l.recIsActive = ToF;
					}
				});
			}

			render(c) {
				c.fillStyle = this.isHovered ? 'orange' : 'rgba(0, 0, 200, 0)';
				c.lineWidth = 1;
				c.strokeStyle = this.isHovered ? 'orange' : 'black';
				c.fill(this.path);
				c.stroke(this.path);
				c.fillStyle = 'black';
			}
		}

		//Klass för att rendera tidsstreck för varje 5 segment.
		class Timeline {
			constructor(x, y, sek) {
				this.x = x;
				this.y = y;
				this.sek = sek;
			}

			render(c) {
				c.beginPath();
				c.lineWidth = 1;
				c.setLineDash([4, 3]);
				c.strokeStyle = 'black';
				c.save();
				c.moveTo(this.x, this.y);

				if (this.y === topY) {
					c.lineTo(this.x, this.y - recHeight);
					c.translate(this.x, this.y - recHeight - 10);
					c.rotate(-Math.PI / 2);
				} else if (this.y === bottomY) {
					c.lineTo(this.x, this.y + recHeight * 2);
					c.translate(this.x, this.y + recHeight * 3 + 10);
					c.rotate(-Math.PI / 2);
				}

				c.fillText(this.sek + ' sek', 0, 0);
				c.stroke();
				c.restore();
				c.setLineDash([0, 0]);
			}
		}

		//Klass för att rendera linjer för likhet.
		class Line {
			constructor(top, bottom, simScore) {
				this.recIsActive = false;
				this.top = top;
				this.bottom = bottom;
				this.simScore = simScore;

				this.top.addLines(this);
				this.bottom.addLines(this);

				this.path = new Path2D();
				this.path.moveTo(top.x + recWidth / 2, top.y + recHeight);
				this.path.lineTo(bottom.x + recWidth / 2, bottom.y);
			}

			render(c) {
				c.strokeStyle = this.recIsActive ? 'orange' : this.style(c);
				c.lineWidth = this.recIsActive ? 3 : this.style(c);
				// const proc = this.simScore * 100;

				if (this.recIsActive && (this.top.isHovered || this.bottom.isHovered)) {
					c.font = 'bold 14px Arial';
					c.fillStyle = this.style(c);
					c.strokeStyle = 'orange';
					c.lineWidth = 4;

					if (this.top.isHovered) {
						c.fillText(
							this.simScore.toFixed(3),
							this.bottom.x + 3,
							this.bottom.y + this.bottom.h / 1.5,
						);
					} else if (this.bottom.isHovered) {
						c.fillText(
							this.simScore.toFixed(3),
							this.top.x + 3,
							this.top.y + this.top.h / 1.5,
						);
					}
				} else {
					c.strokeStyle = this.style(c);
					c.lineWidth = this.style(c);
				}
				c.stroke(this.path);
				c.font = '12px Arial';
				c.fillStyle = 'black';
			}

			style(c) {
				const colors = ['#636363', '#007bff', '#0e0c8a'];

				if (this.simScore >= 0.3 && this.simScore < 0.6) {
					c.lineWidth = 0.5;
					c.strokeStyle = colors[0];
					c.fillStyle = colors[0];
				} else if (this.simScore >= 0.6 && this.simScore < 0.9) {
					c.lineWidth = 1;
					c.strokeStyle = colors[1];
					c.fillStyle = colors[1];
				} else if (this.simScore >= 0.9) {
					c.lineWidth = 2;
					c.strokeStyle = colors[2];
					c.fillStyle = colors[2];
				}
			}
		}

		function visualizeSegmentsAndTimelines(videoLength, y) {
			let x = 50;
			let sek = 0;
			const rectangles = [];

			for (let i = 0; i < videoLength; i++) {
				let r = new Rectangle(x, y, recWidth, recHeight);
				rectangles.push(r);

				if (i % 5 === 0 && i !== 0) {
					if (y === bottomY) {
						let t = new Timeline(x, y, sek);
						timelines.push(t);
					} else {
						let t = new Timeline(x, y, sek);
						timelines.push(t);
					}
				}
				x = x + recWidth;
				sek++;
			}

			return rectangles;
		}

		function simScoreLines(colLeft, colRight) {
			const items = data.filter(
				o =>
					o.query_video_name === queryVideoName &&
					o.reference_video_name === referenceVideoName,
			);
			const lines = [];

			items.forEach(item => {
				let qID = item.query_segment_id;
				let rID = item.reference_segment_id;
				let simScore = item.similarity_score;

				if (simScore >= 0.3 && simScore < 0.6) {
					let line = new Line(colLeft[qID], colRight[rID], simScore);
					lines.push(line);
				} else if (simScore >= 0.6 && simScore < 0.9) {
					let line = new Line(colLeft[qID], colRight[rID], simScore);
					lines.push(line);
				} else if (simScore >= 0.9) {
					let line = new Line(colLeft[qID], colRight[rID], simScore);
					lines.push(line);
				}
			});

			lines.map(line => line.style(c));

			return lines;
		}

		function videoNamesRender(queryVideoName, referenceVideoName) {
			c.font = 'bold 18px Arial';
			c.fillStyle = 'black';
			c.fillText(queryVideoName, 50, topY - recHeight * 2);
			c.fillText(referenceVideoName, 50, bottomY + recHeight * 3);
			c.font = '12px Arial';
		}

		//Canvas settings
		c.canvas.width = window.innerWidth;
		c.canvas.height = window.innerHeight;
		const topY = 100;
		const bottomY = 500;
		const recWidth = 40;
		const recHeight = 25;
		const timelines = [];

		//Videos att jämföra
		const queryVideoName = 'Megamind.avi';
		const referenceVideoName = 'Caterpillar.webm';
		// const referenceVideoName = 'Megamind_bugy.avi';

		//Videons längd
		const queryLength = videoLength(queryVideoName);
		const referenceLength = videoLength(referenceVideoName);

		//Ritar ut rektanglar och retunerar en array med dessa för respektive video.
		const colLeft = visualizeSegmentsAndTimelines(queryLength, topY); //Videons längd, x-värde och namn
		const colRight = visualizeSegmentsAndTimelines(referenceLength, bottomY);

		//Ritar ut likhetsstrecken mellan videonsegmenten
		const lines = simScoreLines(colLeft, colRight);

		const rectangles = [...colLeft, ...colRight];
		const all = [...rectangles, ...lines, ...timelines];

		canvas.addEventListener('mousemove', function(e) {
			const rec = this.getBoundingClientRect();
			const x = e.clientX - rec.left;
			const y = e.clientY - rec.top;

			colLeft.map(r => r.setIsHovered(c.isPointInPath(r.path, x, y)));
			colRight.map(r => r.setIsHovered(c.isPointInPath(r.path, x, y)));
		});

		function onHover() {
			c.clearRect(0, 0, canvas.width, canvas.height);
			videoNamesRender(queryVideoName, referenceVideoName);
			all.map(r => r.render(c));

			requestAnimationFrame(onHover);
		}

		onHover();
	}

	render() {
		return (
			<div>
				<canvas ref="canvas" width={window.width} height={window.height} />
			</div>
		);
	}
}

export default Visualization;
